# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70dba8026819485224907c67d7ccb27f1aff273d7df54b1ba3f65b784de109f7e62e4e571c49f639f070bb8961890b51a7aa8cb507ba4195df60dbcf7bbd9406

test:
  secret_key_base: 58b66f59e959b7b8d2c76982add4ed79ae981bd05a0b5f8d07c832e44cda06c98f89a3d4173b65516c42bb0f5ccba5c3dffe650100a9db44bc2faa5715890b27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
